name: Build & Deploy

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build for production
        run: npm run build
        env:
          CI: false

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          publish_dir: ./build
          publish_branch: gh-pages
          external_repository: vuthanhdatdev/vuthanhdatdev.github.io
          user_name: 'Joe The Dev - GHA'
          user_email: 'vuthanhdat.dev+ci@gmail.com'
          commit_message: 'Deployed by GitHub Actions [run #${{ github.run_number }}]'


