name: Build & Deploy

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node-modules-

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build for production
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          publish_dir: ./build
          publish_branch: gh-pages
          external_repository: vuthanhdatdev/vuthanhdatdev.github.io
          user_name: 'Joe The Dev - GHA'
          user_email: 'vuthanhdat.dev+ci@gmail.com'
          commit_message: 'Deployed by GitHub Actions [run #${{ github.run_number }}]'
